import Advertisement from "../components/Advertisement.js";
import AllPost from "../components/AllBlog.js";
import AllStore from "../components/AllStore.js";
import ArticleNeumadsTrail from "../components/ArticleNeumadsTrail.js";
import Blog from "../components/Blog.js";
import DataFilter from "../components/DataFilter.js";
import DataPost from "../components/DataPost.js";
import DataTags from "../components/DataTags.js";
import DineBlog from "../components/DineBlog.js";
import DineFeaturedBlog from "../components/DineFeaturedBlog.js";
import FeaturedBlog from "../components/FeaturedBlog.js";
import Form from "../components/Form.js";
import createGeocoderInput from "../components/GeocoderInput.js";
import createGeojsonArticleListing from "../components/GeojsonArticleListing.js";
import createGeojsonBlogListing from "../components/GeojsonBlogListing.js";
import createGeojsonListing from "../components/GeojsonListing.js";
import createGeojsonReviewListing from "../components/GeojsonReviewListing.js";
import createGeojsonStoreListing from "../components/GeojsonStoreListing.js";
import geojsonStore from "../components/GeojsonStores.js";
import GeopostReviews from "../components/GeopostReviews.js";
import initMap from "../components/MapApi.js";
import "../components/MapBlog.js";
import "../components/MapFeatures.js";
import createMapMarker from "../components/MapMarker.js";
import {Style2DPrimary, StyleSatellitePrimary} from "../components/MapStyles.js";
import NonFeaturedBlog from "../components/NonFeaturedBlog.js";
import PrimaryFeaturedBlog from "../components/PrimaryFeaturedBlog.js";
import Search from "../components/Search.js";
import SearchFunction from "../components/SearchFunction.js";
import SearchResultsCategory from "../components/SearchResultsCategory.js";
import SearchResultsLocation from "../components/SearchResultsLocation.js";
import ShortsBlog from "../components/ShortsBlog.js";
import ShortsFeaturedBlog from "../components/ShortsFeaturedBlog.js";
import StorePopularTimes from "../components/StorePopularTimes.js";
import UnwindBlog from "../components/UnwindBlog.js";
import UnwindFeaturedBlog from "../components/UnwindFeaturedBlog.js";
import WorkBlog from "../components/WorkBlog.js";
import WorkFeaturedBlog from "../components/WorkFeaturedBlog.js";
import YelpApi from "../components/YelpApi.js";
import YelpReviews from "../components/YelpReviews.js";
import createArticleCard from "../components/card-article.js";
import createBlogCard from "../components/card-blog.js";
import createDefaultCard from "../components/card-default.js";
import createReviewCard from "../components/card-review.js";
import createStoreCard from "../components/card-store.js";
import "../components/grid.js";
import GridOverlay from "../components/gridOverlay.js";
import "../components/groupItems.js";
import listingVariant from "../components/listingVariant.js";
// import locationInput from "../components/locationInput.js";
import mapRoute from "../components/mapRoute.js";
import processGroupedItems from "../components/processGroupedItems.js";
import fetchDateTime from "../components/timeApi.js";
import getWeather from "../components/weatherApi.js";
import "../components/weatherReport.js";